# Generated by Django 4.1.3 on 2022-11-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='tiers', to='images.size'),
        ),
    ]
